name: test_nlp_2
channels:
  - default
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib-inline
  - libffi
  - zlib
  - ca-certificates
  - traitlets
  - decorator
  - jedi
  - xz
  - wheel
  - psutil
  - python-dateutil
  - tornado
  - ncurses
  - appnope
  - debugpy
  - nest-asyncio
  - pyzmq
  - pure_eval
  - stack_data
  - entrypoints
  - openssl
  - pexpect
  - readline
  - zeromq
  - libcxx
  - ipython
  - executing
  - pip
  - tzdata
  - jupyter_client
  - jupyter_core
  - tk
  - six
  - parso
  - sqlite
  - prompt-toolkit
  - pickleshare
  - pygments
  - wcwidth
  - asttokens
  - setuptools
  - certifi
  - ptyprocess
  - backcall
  - libsodium
  - packaging
  - ipykernel
  - spacy
  - pandas
  - tqdm
  - nltk
  - scikit-learn
  - seaborn
  - gensim
  - pyldavis
  - wordcloud
  - plotly
  - yaml
  - pyyaml
  - transformers
  - ipywidgets
  - jupyter-dash
  - sumy
  - pathlib
  - pdf2image
  - opencv
  - pytesseract
  - pillow
  - plotly_express

